Chart.addXAxis = (chart, scale) ->
  xTicks = chart.selectAll('.x-axis')
                .data(scale.ticks(10))
                .enter()
                .append('g')
                .attr('transform', (d) -> "translate(#{scale(d)},#{Chart.height})" )

  xTicks.append('line')
        .classed('x-tick', true)
        .attr('x1', 0)
        .attr('x2', 0)
        .attr('y1', 0)
        .attr('y2', 30)

  xTicks.append('line')
        .classed('x-gridline', true)
        .attr('x1', 0)
        .attr('x2', 0)
        .attr('y1', -Chart.height)
        .attr('y2', 0)

  xTicks.append('text')
        .filter((d) -> d > 0 && d < 100 )
        .classed('x-tick-label', true)
        .text(String)
        .attr('x', 3)
        .attr('y', 29)

Chart.addYAxis = (chart, scale) ->
  yTicks = chart.selectAll('.y-axis')
                .data(scale.ticks(10))
                .enter()
                .append('g')
                .attr('transform', (d) -> "translate(0,#{scale(d)})" )

  yTicks.append('line')
        .classed('y-tick', true)
        .attr('x1', -30)
        .attr('x2', 0)
        .attr('y1', 0)
        .attr('y2', 0)

  yTicks.append('line')
        .classed('y-gridline', true)
        .attr('x1', 0)
        .attr('x2', Chart.width)
        .attr('y1', 0)
        .attr('y2', 0)

  yTicks.append('text')
        .filter((d) -> d > 0 && d < 100 )
        .classed('y-tick-label', true)
        .text(String)
        .attr('x', -29)
        .attr('y', 16)
